### ISSUE TITLE
DEV-VM VBox Default Name could be Taken

### ISSUE THREAD

**Issue by PanadeEdu** [webdevops/vagrant-docker-vm#18]
Minor Bug

Problem:
When installing more than one Instance of the Box, with VirtualBox as Provider, the Box Name "DEV-VM" is already Taken. This is hardcoded in the Vagrantfile.

Possible Solution:
Moving this Configuration to optional Parameter in vm.yml. This way, the only File to be edited is the vm.yml and noth both the Vagrantfile and vm.yml.

**Comment by mblaschke** [comment]
Name is already moved to `vm.yml`
